import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import gql from 'graphql-tag'
import useQGLQuery  from '../utils/useGQLQuery';
import { useState } from 'react';

const GET_COUNTRIES = gql`
  query{
    countries {
      code
      name
    }
  }
`;

export default function Home() {
  const data = useQGLQuery('countries', GET_COUNTRIES);
  const [value, setValue] = useState('AD');
  if(data.isLoading) return 'loading countries...';
  if(data.error) return 'something went wrong...';
  console.log(data.data);
  return (
    <div>
      <Head>
        <title>Task</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <h1>Select a country</h1>
        <select onChange={e => setValue(e.target.value)} value={value}>
          {data.data.countries.map((country: any): JSX.Element => (
            <option value={country.code} key={country.code}>{country.name}</option>
          ))}
        </select>
        <Link as={`/country/${value}`} href={`/country?code=${value}`}>
          <button>Details</button>
        </Link>
      </div>
    </div>
  )
}